name: yo-listen
services:
  pg:
    image: postgres
    container_name: pg
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backups:/backups

    

  mail:
    image: maildev/maildev
    container_name: mail-dev
    environment:
      - TZ=Europe/Moscow
      - MAIL_DEV_PORT=1080
      - MAIL_DEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  backups:
    image: postgres
    container_name: pg_backup
    env_file:
      - .env.docker
    volumes:
      - ./backups:/backups
    command: | 
      bash -c "
          pg_dump -h pg -U $${POSTGRES_USER} $${POSTGRES_DB} > /backups/backup_$$(date +%Y%m%d_%H%M%S).sql
          echo 'Backup created!'
        "
    depends_on:
      - pg
    profiles: ["backup"]

volumes:
  postgres-data: 